### ISSUE TITLE
make the custom option translatable

### ISSUE THREAD

**Issue by Dontorpedo** [0x15f/select-or-text#1]
Hi,

how can i translate the "Custom (Free Text)" Option?

**Comment by lintaba** [comment]
you can send a PR to https://github.com/0x15f/select-or-text/blob/master/resources/js/components/FormField.vue#L29

**Comment by 0x15f** [comment]
I didn't get an email for this for some reason. I'll implement that.

**Comment by 0x15f** [comment]
Just implemented, add `Custom (Free Text)` as a translation.

**Comment by lintaba** [comment]
You missed the {{}}

**Comment by 0x15f** [comment]
Whoops, thank you for the PR.
